---
default_language_version:
    python: python3

repos:
    # Meta hooks
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes

    # Security & credential scanning/alerting
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: debug-statements
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
          - id: detect-private-key
          - id: check-builtin-literals
          - id: check-shebang-scripts-are-executable
          - id: check-yaml
          - id: check-toml
          - id: check-case-conflict
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: mixed-line-ending
          - id: check-ast

    # Formatters that may modify source files automatically
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.21.2
      hooks:
          - id: pyupgrade
            args: ["--py38-plus", "--keep-runtime-typing"]

    # Linters and validation
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.11
      hooks:
          - id: ruff-format
            args:
                - "."
            pass_filenames: false
          - id: ruff-check
            args:
                - "--fix"
                - "--exit-non-zero-on-fix"
                - "--statistics"
                - "--output-format=concise"
                - "."
            pass_filenames: false

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.19.1"
      hooks:
          - id: mypy
            args: ["--config-file", "pyproject.toml", "thefuck/"]
            files: "^thefuck/.*"
            pass_filenames: false

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-check-blanket-noqa
          - id: python-check-blanket-type-ignore
          - id: python-check-mock-methods
          - id: python-no-eval
          - id: python-no-log-warn

    - repo: https://github.com/jendrikseipp/vulture
      rev: "v2.14"
      hooks:
          - id: vulture
            args:
                - --min-confidence
                - "100"
                - --sort-by-size
                - "thefuck/"
                - "tests/"

    - repo: https://github.com/pycqa/bandit
      rev: 1.9.2
      hooks:
          - id: bandit
            args:
                - "-c"
                - "pyproject.toml"
                - "--quiet"
                - "thefuck/"
            # Needed if using pyproject.toml for config
            additional_dependencies: ["bandit[toml]"]
            pass_filenames: false
    # GHA linting
    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: "0.36.0"
      hooks:
          - id: check-github-workflows
          # - id: check-readthedocs
          - id: check-dependabot
