[tox]
runner = uv-venv-lock-runner
skipsdist = True
envlist = py{310,311,312,313,314}
requires =
    tox >= 4.4.6
    tox-uv
provision_tox_env=provision
all_sources = thefuck/ tests/

passenv =
    SSH_AUTH_SOCK

allowlist_externals =
    uv
    pre-commit
    python
    true

commands_pre = uv sync

[testenv]
commands =
    ; uv run ruff format --diff {posargs:.}
    # uv run ruff check --no-fix --statistics --output-format concise {posargs:.}
    # uv run mypy --cache-dir /dev/null {posargs:src}
    uv run pytest -v --capture=sys

[testenv:debug]
description = Run pytest with args (default '--lf --pdb')
commands =
    uv run pytest {posargs:--lf --pdb}
